version: "3.3"
services:
  ngnix:
    image: nginx
    ports:
      - "8080:80"
    configs:
      - source: nginx_config
        target: /etc/nginx/nginx.conf
    secrets:
      - cacert
      - nginx_cert
      - nginx_key
  rabbitmq:
    image: rabbitmq
    ports:
      - "5672:5672"
      - "5671:5671"
      - "15671:15671"
    configs:
      - source: rabbitmq_config
        target: /etc/rabbitmq/rabbitmq.config
      - source: rabbitmq_enabled_plugins
        target: /etc/rabbitmq/enabled_plugins
      - source: rabbitmq_definitions
        target: /etc/rabbitmq/definitions.json
    secrets:
      - cacert
      - rabbitmq_cert
      - rabbitmq_key
  # in the future, can cluster using cassandra-1, cassandra-2, ...
  # is there a good way to handle this with replicas?
  cassandra:
    image: cassandra
    ports:
      - "9042:9042"
  web:
    image: beehive-web
    deploy:
      replicas: 3
  loader:
    image: beehive-loader
    secrets:
      - cacert
configs:
  nginx_config:
    file: ./configs/nginx/nginx.conf
  rabbitmq_config:
    file: ./configs/rabbitmq/rabbitmq.config
  rabbitmq_definitions:
    file: ./configs/rabbitmq/definitions.json
  rabbitmq_enabled_plugins:
    file: ./configs/rabbitmq/enabled_plugins
secrets:
  cacert:
    external: true
  rabbitmq_cert:
    external: true
  rabbitmq_key:
    external: true
  nginx_cert:
    external: true
  nginx_key:
    external: true
