version: "3.3"
services:
  ngnix:
    image: nginx
    ports:
      - "8080:80"
    configs:
      - source: nginx.conf
        target: /etc/nginx/nginx.conf
  rabbitmq:
    image: rabbitmq
    ports:
      - "5672"
      - "5671:5671"
      - "15671:15671"
    volumes:
      - ./rabbitmq-config:/etc/rabbitmq
    secrets:
      - cacert
      - rabbitmq_cert
      - rabbitmq_key
  # in the future, can cluster using cassandra-1, cassandra-2, ...
  # is there a good way to handle this with replicas?
  cassandra:
    image: cassandra
    ports:
      - "9042:9042"
  web:
    image: beehive-web
    deploy:
      replicas: 3
configs:
  nginx.conf:
    file: ./nginx.conf
secrets:
  cacert:
    external: true
  rabbitmq_cert:
    external: true
  rabbitmq_key:
    external: true
