version: "3.1"
services:
  ngnix:
    image: beehive-nginx
    ports:
      - "8080:80"
  rabbitmq:
    image: beehive-rabbitmq
    ports:
      - "5671:5671"
      - "15671:15671"
    secrets:
      - cacert
      - rabbitmq_cert
      - rabbitmq_key
  cassandra:
    image: beehive-cassandra
  web:
    image: beehive-web
    deploy:
      replicas: 3
secrets:
  cacert:
    external: true
  rabbitmq_cert:
    external: true
  rabbitmq_key:
    external: true
