version: "3.1"
services:
  ngnix:
    image: beehive-nginx
    ports:
      - "8080:80"
  rabbitmq:
    image: beehive-rabbitmq
    ports:
      - "5671:5671"
      - "15671:15671"
    secrets:
      - cacert
      - rabbitmq_cert
      - rabbitmq_key
  # in the future, can cluster using cassandra-1, cassandra-2, ...
  # is there a good way to handle this with replicas?
  cassandra:
    image: cassandra
    ports:
      - "9042:9042"
  web:
    image: beehive-web
    deploy:
      replicas: 3
secrets:
  cacert:
    external: true
  rabbitmq_cert:
    external: true
  rabbitmq_key:
    external: true
